apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: IDS-api-components
  description: A collection of all Backstage example components
spec:
  targets:
    - ./components/cdp-component.yaml
    - ./components/cdp2-component.yaml
    - ./components/ids-api-component.yaml
    - ./components/ids-lists-component.yaml
    - ./components/ids-smev-component.yaml

