apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ids-smev
  # This is an extra long description
  description: проверка паспорта в ids
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: production
  owner: KYC
  system: IDS-API

